default:
  outputs:
    test: # Keypair config
      type: snowflake
      account: xk23394.eu-west-1
      user: DBT_EXAMPLE_USER
      role: DBT_EXAMPLE_ROLE
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: DBT_EXAMPLE_DB
      warehouse: COMPUTE_WH
      schema: DBT_SCHEMA
      threads: 1
      client_session_keep_alive: False